### ISSUE TITLE
[Bug] Can't add files to React project.

### ISSUE THREAD

**Issue by SuzieZUMO** [creativetimofficial/ct-material-kit-pro-react#100]
### Version
1.0
### Reproduction link
https://github.com/SuzieZUMO/medexplainweb
### Operating System
Windows 11
### Device
a pc laptop
### Browser & Version
Firefox, latest, but NA
### Steps to reproduce
I followed the instructions to try to add the template we purchased. 
Full results are below.  Help?

PS C:\Users\sansp\Source\Repos\medexplain\mefrontend> npm install @material-ui/core
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: mefrontend@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from @material-ui/core@4.12.4
npm ERR! node_modules/@material-ui/core
npm ERR!   @material-ui/core@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\sansp\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sansp\AppData\Local\npm-cache\_logs\2022-06-17T19_27_59_568Z-debug-0.log
PS C:\Users\sansp\Source\Repos\medexplain\mefrontend> npm install --legacy-peer-deps

removed 1 package, and audited 1422 packages in 3s

192 packages are looking for funding
  run `npm fund` for details

6 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
PS C:\Users\sansp\Source\Repos\medexplain\mefrontend> npm install @material-ui/core
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: mefrontend@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from @material-ui/core@4.12.4
npm ERR! node_modules/@material-ui/core
npm ERR!   @material-ui/core@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\sansp\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sansp\AppData\Local\npm-cache\_logs\2022-06-17T19_34_04_959Z-debug-0.log
### What is expected?
The files install in my project.
### What is actually happening?
The files do not install in my project.

---

**Comment by sajadevo** [comment]
**Hi @SuzieZUMO**

Thanks for using our product please run the following command: `npm i --legacy-peer-deps`

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**

**Comment by SuzieZUMO** [comment]
Okay, thank you. I fixed it like this:
 npm install @material-ui/core --legacy-peer-deps

Should I be worried about this?  **6 high severity vulnerabilities**
