### ISSUE TITLE
[Bug] Compile error on first starting the project files downloaded from my Creative Tim account

### ISSUE THREAD

**Issue by babylon2017** [creativetimofficial/ct-material-kit-pro-react#105]
### Version
2.0.0
### Reproduction link
https://www.creative-tim.com/learning-lab/react/quick-start/material-kit/
### Operating System
Mac OS
### Device
desktop
### Browser & Version
Chrome 104.0.5112.79 
### Steps to reproduce
1. Download React project file
2. yarn install
3. yarn start
### What is expected?
a working website as described in https://www.creative-tim.com/learning-lab/react/quick-start/material-kit/
### What is actually happening?
Compile error.
Multiple error messages of the type: 
"Prop type object is forbidden" 
<img width="571" alt="Screenshot 2022-08-07 at 07 14 58" src="https://user-images.githubusercontent.com/28309148/183280752-cc47c8d5-b78c-4dda-823d-7f360844b1e8.png">

This error message is spread over several files

---

**Comment by SeizeTheFuture** [comment]
I had the same issue. I was able to resolve it by replacing all those instances of PropTypes.object with the following: PropTypes.objectOf(PropTypes.shape()). Best of luck.
