### ISSUE TITLE
[Bug] Doesn't compile with npm 1.18 and react-script 5 and swiper 7

### ISSUE THREAD

**Issue by rastaman** [creativetimofficial/ct-material-kit-pro-react#106]
### Version
2.0
### Reproduction link
https://gist.github.com/rastaman/59dbe8e49325f31170a3952bf8f853aa
### Operating System
MacOS Ventura
### Device
Macbook Pro
### Browser & Version
Chrome 108
### Steps to reproduce
Compile with npm 1.18, react-script 5 and swiper 7, it fails.

### What is expected?
Compiling and starting the application should work.
### What is actually happening?
It fails with errors.

---
### Solution
I patched the source to use updated swiper imports, react-scripts 5 and changed the way the context is created in MKPagination.
### Additional comments
Feel free to offer me a company licence on my order for this patch, i will use it well and help to maintain it :-) Happy new year!

**Comment by rastaman** [comment]
Patch is here: https://gist.github.com/rastaman/3fe714f4f4977acd9c23d4f082def860

**Comment by sajadevo** [comment]
Hey there,

We've updated the product and this issue is not happening, you should update to the latest version of NPM in order to work with the product.

Regards,
Sajad
