### ISSUE TITLE
[Bug] npm install is not running to my project which is not working.

### ISSUE THREAD

**Issue by pratikgupta556** [creativetimofficial/ct-material-kit-pro-react#107]
### Version
Latest Download from Club dashboard
### Reproduction link
https://github.com/creativetimofficial/ct-material-kit-pro-react/issues/new
### Operating System
windows
### Device
Dell inspiron Laptop
### Browser & Version
Chrome latest
### Steps to reproduce
1 do npm install
2 
### What is expected?
npm install, npm run should work. 
### What is actually happening?
I get vulnerablities error and then project doesnt start 

---

**Comment by sajadevo** [comment]
Hey @pratikgupta556,

Thanks for using our product, could you please send me the error you've received?

Regards,
Sajad

**Comment by sajadevo** [comment]
Hey there,

We've updated the product and the installation issue is fixed now.

Regards,
Sajad
