### ISSUE TITLE
React-Popper error

### ISSUE THREAD

**Issue by mdixon47** [creativetimofficial/ct-material-kit-pro-react#11]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior
./src/components/CustomDropdown/CustomDropdown.jsx
185:10-16 'react-popper' does not contain an export named 'Target'.

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:MacBook Pro
* Operating System: OS X 10.14
* Browser and Version: Chrome Version 68.0.3440.106 (Official Build) (64-bit)

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by einazare** [comment]
Hello @mdixon47 ,

Thank you for your interest in using our product.
Please take the latest version of this product, we have solved it in our latest version.

Best,
Manu
