### ISSUE TITLE
[Bug] [eslint] Plugin "react" was conflicted between ".eslintrc.json" and "BaseConfig » node_modules\eslint-config-react-app\base.js" webpack compiled with 1 error

### ISSUE THREAD

**Issue by HyeJinChoiAmkor** [creativetimofficial/ct-material-kit-pro-react#112]
### Version
2.1.0
### Reproduction link
http://localhost:3000/
### Operating System
Windows 11 Enterprise
### Device
Any*
### Browser & Version
Chrome 126.0.6478.128
### Steps to reproduce
1. Type the command 'npm start' in terminal
2. The error encounters 'Failed to compile.'
3. Whenever refreshing the browser, the error shows up in the screen.
### What is expected?
no error
### What is actually happening?
the error is shown in the browser.

---

**Comment by sajadevo** [comment]
This issue is fixed on v2.1.1
