### ISSUE TITLE
Footer CSS bug in mobile display

### ISSUE THREAD

**Issue by zequnyu** [creativetimofficial/ct-material-kit-pro-react#12]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

In the demo of [login page](https://demos.creative-tim.com/material-kit-pro-react/#/login-page), the footer doesn't show correctly from mobile view.

![wechatimg31](https://user-images.githubusercontent.com/18158257/45356573-214bd400-b5f6-11e8-9416-4bec96bb8157.png)

**Comment by einazare** [comment]
Hello again @zequnyu ,

Thank you for pointing us this issue.
To solve it go inside `src/assets/jss/material-kit-pro-react/views/loginPageStyle.jsx` and do the following changes:

 - 
```
container: {
    ...container,
    zIndex: "2",
    position: "relative",
    paddingTop: "20vh",
    color: "#FFFFFF"
  },
```
should be changed to
```
container: {
    ...container,
    zIndex: "4",
    [theme.breakpoints.down("sm")]: {
      paddingBottom: "100px"
    }
  },
```
 - 
```
pageHeader: {
    minHeight: "100vh",
    maxHeight: "1000px",
    height: "auto",
    display: "inherit",
    position: "relative",
    margin: "0",
    padding: "0",
    border: "0",
    alignItems: "center",
```
should be changed to
```
pageHeader: {
    color: "#fff",
    border: "0",
    height: "100%",
    margin: "0",
    display: "flex!important",
    padding: "120px 0",
    position: "relative",
    maxHeight: "1000px",
    minHeight: "100vh",
    alignItems: "center",
```
 - 
```
const signupPageStyle = {
```
should be 
```
const signupPageStyle = theme => ({
```
 - 
and 
```
};

export default signupPageStyle;
```
should be
```
});

export default signupPageStyle;
```

Hope this info helps you.

Best,
Manu
