### ISSUE TITLE
Upgrade Material UI ^3.0

### ISSUE THREAD

**Issue by miiga** [creativetimofficial/ct-material-kit-pro-react#13]
When will material UI:^3.0 version released ?

**Comment by einazare** [comment]
Hello there @miiga ,

And thank you for your interest in using our product.
As of moment we have a lot on our hands and we did not start the update for this product.
When we will have somewhere around 10-20 requests of updating this product to a newer version, we will do so, or maybe we will have some free time and update it in a couple of weeks.

Best,
Manu

**Comment by clindsey** [comment]
please upgrade to material-ui v3

**Comment by einazare** [comment]
Hello again @clindsey ,

I am very sorry, but in the following 1-2 weeks, we have some other, much more important issues to attend to. We are doing the best of what we can. I am going to speak to the board and see what they decide.

Best,
Manu

**Comment by clindsey** [comment]
at least please make it very obvious on the purchase page that this is using an outdated version of material-ui.  I'm surprised that material-ui.com even recommends this product, I definitely would not have paid for it if I had known it was so outdated

I didn't look closely at the free version because it was missing a lot of the example pages from the pro version

**Comment by einazare** [comment]
Hello again @clindsey ,

Sorry for this inconvenience.
The board has decided to start the update of the Material products, and i hope it will be done by the end of next week.

Best,
Manu

**Comment by acmitch** [comment]
@EINazare when we this release be available from Creative Tim?

**Comment by einazare** [comment]
Hello there @acmitch ,

Thank you for your interest in working with our products.
The update was done 10 days ago both on Github and Tim platform.
Are you having difficulties downloading the newer version of the product?

Best,
Manu

**Comment by acmitch** [comment]
When looking at the changelog, I was confused by the date. I now see issue 13, sorry for the noise.

![image](https://user-images.githubusercontent.com/4482055/46684150-9a1f5b00-cbb7-11e8-8d0e-8571fbed068c.png)

**Comment by einazare** [comment]
Hello again @acmitch ,

Sorry about this. It seems I've put 08 instead of 09.
You are right, people could get confused by that.
In a bit, I will change that.

Best,
Manu
