### ISSUE TITLE
Feature Request:  nested comment sample

### ISSUE THREAD

**Issue by haysclark** [creativetimofficial/ct-material-kit-pro-react#19]
It would be really great to have a nested comment sample.

Ideally, something like this:
https://semantic-ui.com/views/comment.html

**Comment by einazare** [comment]
Hello there @haysclark  ,

Actually, we have this implemented here: [https://demos.creative-tim.com/material-kit-pro-react/#/blog-post](https://demos.creative-tim.com/material-kit-pro-react/#/blog-post)
![screen shot 2018-10-30 at 5 59 05 pm](https://user-images.githubusercontent.com/26245512/47731791-83779b80-dc6d-11e8-8de2-3ccf3375fcf5.png)
As you can see the second comment is a bit slightly to the right, meaning that comment is a nested comment for the first one.
That is part of the [Media components](https://demos.creative-tim.com/material-kit-pro-react/#/documentation/media).
Is this what you were looking for?


Best,
Manu
