### ISSUE TITLE
Broken links on Styles page

### ISSUE THREAD

**Issue by estaub** [creativetimofficial/ct-material-kit-pro-react#2]
The three links at the top of [the Styles page](https://demos.creative-tim.com/material-kit-pro-react/#/documentation/styles) are broken.  I believe the one I needed, about override approach, is supposed to refer to https://material-ui.com/customization/overrides/#3-specific-variation-of-a-component

**Comment by einazare** [comment]
Hello @estaub ,

Thank you for your interest in using our products and sorry for this late response.
On our next update we are going to fix this.

Best,
Manu
