### ISSUE TITLE
Paragraph tag in InfoArea description

### ISSUE THREAD

**Issue by MincePie** [creativetimofficial/ct-material-kit-pro-react#22]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

# Expected Behavior

Is it possible to use a paragraph or br tag in the description field on an InfoArea element?

# Current Behavior

Long paragraphs seem to be the only option 

# Failure Information (for bugs)

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by einazare** [comment]
Hello again @MincePie ,

Yes, you can do that.
Here is an example:
```
<InfoArea
            title="1. Design"
            description={
              <span>
                <p>
                  The moment you use Material Kit, you know you’ve never felt
                  anything like it. With a single use, this powerfull UI Kit
                  lets you do more than ever before.{" "}
                </p>
                <br/>
                <p>
                  The moment you use Material Kit, you know you’ve never felt
                  anything like it. With a single use, this powerfull UI Kit
                  lets you do more than ever before.{" "}
                </p>
              </span>
            }
            icon={Gesture}
            iconColor="rose"
          />
```
The only thing is that you would have to enclose them in a wrapper tag, in my example, I've used a `<span>...</span>` tag.
Hope this information helps you.

Best,
Manu
