### ISSUE TITLE
Missing Button and slighlty different different font when integrating with Next js

### ISSUE THREAD

**Issue by tylim88** [creativetimofficial/ct-material-kit-pro-react#23]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

should be look exactly the same like demo

# Current Behavior

Missing Button and slighlty different different font

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Integrate it into Next js following this post
https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues/72

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: PC
* Operating System: Win 10
* Browser and Version: Chrome 70

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by tylim88** [comment]
![2](https://user-images.githubusercontent.com/5227509/49536104-b9f5a580-f900-11e8-84e5-1dce78e593e6.png)
Side note, not sure this is intended or not, the icon of make edit is off, i changed it to Edit and it look the same with demo
![1](https://user-images.githubusercontent.com/5227509/49536002-7e5adb80-f900-11e8-9f0d-26e1bb1a69cb.png)

**Comment by tylim88** [comment]
![1](https://user-images.githubusercontent.com/5227509/49536254-08a33f80-f901-11e8-8859-7ecbceae23a6.png)
![2](https://user-images.githubusercontent.com/5227509/49536358-430cdc80-f901-11e8-909d-a62c5c5650a4.png)

Back to my question, the font is slightly off and the button is missing, I am following guide in https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues/72

update: solved one of the problems, now the brand is showing
![image](https://user-images.githubusercontent.com/5227509/49564743-944bb900-f95f-11e8-8b9f-2d194c717f39.png)

**Comment by tylim88** [comment]
in case it is required, my order number is #86534289

**Comment by einazare** [comment]
Hello there @tylim88 ,

Thank you for your interest in working with our products.
You are actually missing our fonts and styles links from the public/index.html file.
Just copy those in your index.html file, and everything should be fine.
Also, please check our src/index.js, we also have there some styles imported.
You'll need those as well.

Best,
Manu

**Comment by tylim88** [comment]
Thank ElNazare, that was a quick fix!

seem like all pages are working now

**Comment by dray356** [comment]
Hi @EINazare ,

I donwload, npm install, and then npm start the project and it has similar styling issues right off the bat. I went to the _misc.scss file and changed every font size and the Header fonts are still tiny for some reason, as is the title on the views/PresentationPage/PresentationPage.jsx. I haven't touched the index.html file nor the index.js file.

Any advice?

**Comment by einazare** [comment]
Hello there, @dray356 ,

Please make a video with the following:
- Download the product
- Unzip the product
- Open terminal and cd into the project
- Run `npm run install:clean`
- Showcase the issue

Best,
Manu
