### ISSUE TITLE
Feature request - add loading spinner component

### ISSUE THREAD

**Issue by thclark** [creativetimofficial/ct-material-kit-pro-react#27]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Feature request

It would be nice to have a loading spinner component, delivering a nice looking spinner rendered in the center of the viewport.

The use case is when fetching a resource (e.g. blog page content, or whatever) from an API, in the 1-2s roundtrip time I want to render a blank page with a spinner to show the user that something will happen soon.

This is a minor component, not too hard to build oneself, but it'd make a convenient addition to the kit.

**EDIT: BONUS:** I developed [this component](https://stackoverflow.com/a/54112855/3556110) to help render a loading spinner in center page with the material grid container, when waiting for page data

**Comment by einazare** [comment]
Hello there @thclark ,

Thank you for your interest in working with our products.
I'll forward your request to our board, and I think in a future update we'll add this, since there were other users that have requested this, and the spinner loader is something that is starting to become a must in an application.

Best,
Manu

**Comment by thclark** [comment]
Thanks Manu... I can think of two use cases:
 - [ ] A blank page where it just sits centrally, fairly large
 - [ ] A smaller one a for div occupying some part off the screen in a wider web app, e.g. while some particular sub-resource loads.

**Comment by thclark** [comment]
Chucked up a demo too...
[https://tpast.herokuapp.com/loading](https://tpast.herokuapp.com/loading)

**Comment by rimoslav** [comment]
Hello @thclark, can you share the source code for that component you made? I don't really like the one I've made myself.

**Comment by thclark** [comment]
Sure @rimoslav I created a gist.
https://gist.github.com/thclark/e637954f774c17c097f29d765492a377

@EINazare feel free to use the same or adapt for inclusion straight into material kit pro (you'd just need to change back to your style guide, as I use airbnb)... no license but the decent thing to do would be to send me something nice ;)

**Comment by rimoslav** [comment]
Thanks @thclark!

**Comment by einazare** [comment]
Hello there @thclark ,

Thank you for sharing with us your code snippet.
In a few weeks, we'll have a board meeting and will tell our board about this.

Best,
Manu

**Comment by rimoslav** [comment]
Hey @thclark, could I trouble you for that FullArea component used in LoadingPage?

**Comment by thclark** [comment]
Oops, sorry @rimoslav that was actually the main effort getting the centring correct! It's a useful thing in its own right (see https://stackoverflow.com/a/54112855/3556110 for its background), so I added it to a separate gist...
https://gist.github.com/thclark/df7c424c9fb9ff6ee0f5fea81b072493

**Comment by rimoslav** [comment]
@thclark Thanks a trillion!

**Comment by thclark** [comment]
You're most welcome. Glad it's coming to some use!

**Comment by sajadevo** [comment]
**Hi there**,

We've just updated the product to v2.0.0 and now its coming with a totally new structure, fresh design and new look.

**All the best**
**Sajad**
