### ISSUE TITLE
Feature Request: Bootstrap Sidebar Collapse

### ISSUE THREAD

**Issue by eleventhaus** [creativetimofficial/ct-material-kit-pro-react#28]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Hoping that there is an easy way to mod the AppBar so that we can use the [default bootstrap sidebar collapse](https://github.com/creativetimofficial/ct-material-kit-pro/issues/49).

# Current Behavior

Sidebar slides out from the right

# Failure Information (for bugs)

none

## Context

I understand the AppBar component is probably coded to work for react-native but the option to use the bootstrap default collapse would be appreciated!

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by einazare** [comment]
Hello again, @eleventhaus ,

Unfortunately, this product does not use bootstrap.
It is built only on Material-UI framework.
I am not sure I can do anything here.

Best,
Manu

**Comment by eleventhaus** [comment]
ok thanks
