### ISSUE TITLE
Wiring <Field> from Redux-Form to <CustomInput> from material-ui

### ISSUE THREAD

**Issue by eleventhaus** [creativetimofficial/ct-material-kit-pro-react#29]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Expected to be able to pass <CustomInput> into component attribute on <Field>

# Current Behavior

The value of the CustomInput isn't matching up with the Field value in ReduxForm

# Failure Information (for bugs)

Input props is showing on console but unable to connect it to CustomInput component

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

```
import { Field, reduxForm } from "redux-form";

<Field
     name="additional_info"
     component={CustomInput}
     labelText="Additional Info"
     id="additional_info"
     formControlProps={{
          fullWidth: true
     }}
     inputProps={{
          multiline: true,
          rows: 5
     }}
/>
```

Console -
![screen shot 2019-01-12 at 1 02 44 pm](https://user-images.githubusercontent.com/34343079/51078498-62b6c380-166a-11e9-9bd5-a78b6a0ecd1d.png)

CustomInput.jsx
```
import Input from "@material-ui/core/Input";

const {
      classes,
      formControlProps,
      labelText,
      id,
      labelProps,
      inputProps,
      error,
      white,
      inputRootCustomClasses,
      success,
      input <------????????
    } = props;

<Input
     classes={{
          input: inputClasses,
          root: marginTop,
          disabled: classes.disabled,
         underline: underlineClasses
     }}
     id={id}
     {...inputProps}
     {...input} <----?????
        />
```

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by einazare** [comment]
Hello there @eleventhaus 

I really do not understand your issue.
Why use Field from react-redux instead of our CustomInput?
It doesn't really make sense to me.

Best,
Manu

**Comment by eleventhaus** [comment]
My app uses Redux for state management. Is there another way to use Redux with CustomInput?

I'd like to use CustomInput for the template styling AND Redux for state management, together. Is that possible?

**Comment by einazare** [comment]
Hello again, @eleventhaus ,

From what I know, Redux is used for state management.
I do not really see why you would need to work with their input, instead of ours.
You just send the state from Redux to our input as it's value, and you can assign an onChange handler for our CostumInput and that handler should call an action or action creator to your Redux.
But that is just how I would go about it.

Here is my tutorial on Redux: https://medium.freecodecamp.org/how-to-use-redux-in-reactjs-with-real-life-examples-687ab4441b85
And the Youtube one: https://www.youtube.com/watch?v=raKV5Rb8oOM&list=PLWxSJr7LCl87rGlQtTo2PoX8hboUU0R8a

Also, you can find more on the internet.

Hope this information will help you.

Best,
Manu

**Comment by eleventhaus** [comment]
> I do not really see why you would need to work with their input, instead of ours.

I'd like to use both. I would like to use `<CustomInput>` for styling purposes

> You just send the state from Redux to our input as it's value, and you can assign an onChange handler for our CustomInput

Redux-form does this all easily if you wire up their <Field> component to an already exists component like `<CustomInput>`. The problem is I'm having trouble connecting the two

**Comment by eleventhaus** [comment]
Figured it out for anyone else who might need it

Use `CustomInput` in the component attribute in the Field component.
```
import { Field, reduxForm } from "redux-form";

<Field
     name="additional_info"
     component={CustomInput} <----- here
     labelText="Additional Info"
     id="additional_info"
     formControlProps={{
          fullWidth: true
     }}
     inputProps={{
          multiline: true,
          rows: 5
     }}
/>
```
In CustomInput add `input` and `value` to props and then add `value={value}` and `onChange={input.onChange}` to <Input> component

```
import Input from "@material-ui/core/Input";

const {
      classes,
      formControlProps,
      labelText,
      id,
      labelProps,
      inputProps,
      error,
      white,
      inputRootCustomClasses,
      success,
      input, <-------------------- here
      value  <-------------------- here
    } = props;

<Input
     classes={{
          input: inputClasses,
          root: marginTop,
          disabled: classes.disabled,
         underline: underlineClasses
     }}
     id={id}
     {...inputProps}
     
        />


return (
    <FormControl {...formControlProps} className={formControlClasses}>
      {labelText !== undefined ? (
        <InputLabel
          className={classes.labelRoot + " " + labelClasses}
          htmlFor={id}
          {...labelProps}
        >
          {labelText}
        </InputLabel>
      ) : null}
      <Input
        classes={{
          input: inputClasses,
          root: marginTop,
          disabled: classes.disabled,
          underline: underlineClasses
        }}
        id={id}
        {...inputProps}
        value={value}  <-------------------- here
        onChange={input.onChange} <-------------------- here
      />
      {error ? (
        <Clear className={classes.feedback + " " + classes.labelRootError} />
      ) : success ? (
        <Check className={classes.feedback + " " + classes.labelRootSuccess} />
      ) : null}
    </FormControl>
  );

```
