### ISSUE TITLE
Module not found: Can't resolve '@babel/runtime/helpers/builtin/assertThisInitialized'

### ISSUE THREAD

**Issue by sagarkt** [creativetimofficial/ct-material-kit-pro-react#3]
Just purchased the pro version and tried to start by following [these steps](https://demos.creative-tim.com/material-kit-pro-react/?_ga=2.1110705.1235853670.1533727674-1797633235.1533727674#/documentation/tutorial). But encountered below error.

Nothing did anything extra. I just followed the steps.

    `Failed to compile.

    ./node_modules/@material-ui/core/ButtonBase/TouchRipple.js
    Module not found: Can't resolve '@babel/runtime/helpers/builtin/assertThisInitialized' in '/Users/sagarkamble/hobby_projects/rento/material-kit-pro-react-v1.0.0/node_modules/@material-ui/core/ButtonBase'`

Version: material-kit-pro-react - 1.0.0

**Comment by einazare** [comment]
Hello @sagarkt ,

Thank you for your interest in using our products and sorry for this late response.
A quick fix for this is to run `npm install --save-exact @babel/runtime@7.0.0-beta.55` and it will work.
We are going to fix this in our next update (which i believe it will be done this week).

Best,
Manu

**Comment by ryuujo** [comment]
I have the same problem with this and already try with your fix, but it still not working

**Comment by einazare** [comment]
Hello there @irobertjr ,

Download again the product.
In one of our updates we've solved this issue.

Best,
Manu

**Comment by MelMacaluso** [comment]
From another topic, this fixed it:

`npm add @babel/runtime`

**Comment by UnnitMetaliya** [comment]
> From another topic, this fixed it:
> 
> `npm add @babel/runtime`

Thank you very much. I did not have the issue OP posted. I had helper/slicedToArray issue. Google brought me here and your comment solved it. Thanks @MelMacaluso 👍

**Comment by jaegz** [comment]
I too ran into the slicedToArray issue. Deleting `node_modules`, `yarn.lock`, `package-lock.json` and running `npm install` fixed it for me.

**Comment by amaanrajput940** [comment]
> 
> 
> From another topic, this fixed it:
> 
> `npm add @babel/runtime`

Still is not working while I am using this version "@babel/runtime": "^7.5.5", 
I'm getting this error
 ./node_modules/react-popper/lib/cjs/Popper.js
Module not found: Can't resolve '@babel/runtime/helpers/objectWithoutPropertiesLoose' in 'E:\reactjs\deveans-react-version\node_modules\react-popper\lib\cjs'

**Comment by hanzlahabib** [comment]
i am still facing this issue in latest version of babel/runtime

./node_modules/@material-ui/core/ButtonBase/ButtonBase.js                                                                                                                                       Module not found: Can't resolve '@babel/runtime/helpers/builtin/assertThisInitialized' in 'F:\Projects\nuton-admin\node_modules\@material-ui\core\ButtonBase'
--

**Comment by einazare** [comment]
Hello there, @hanzlahabib ,

Have you made changes to our package.json?
If I run a clean install everything works fine.

Best,
Manu

**Comment by hanzlahabib** [comment]
Manu i will try this

  Thank you for responding
