### ISSUE TITLE
Pagination Component

### ISSUE THREAD

**Issue by hbariki** [creativetimofficial/ct-material-kit-pro-react#30]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [v1.2.0 ] I am running the latest version
- [ Yes] I checked the documentation and found no answer
- [Yes ] I checked to make sure that this issue has not already been filed

# Expected Behavior
I am trying to import pagination component in order to implement pagination in one of my web pages. I am using material Pro Kit React 1.2.0 version.
# Current Behavior

Hi I have imported pagination component into my application in order to build pagination into one of my web pages. But some how it shows me an error in pagination.jsx. When I imported other components like Buttons and headers it worked. Does pagination component works in material pro kit react v1.2.0

**Comment by einazare** [comment]
Hello there, @hbariki ,

And thank you for your interest in working with our product.
We do have Pagination in our product as you can see in this page here: https://demos.creative-tim.com/material-kit-pro-react/#/components
In the content areas and the basic components (use the right dots).
![screen shot 2019-01-30 at 10 14 43 am](https://user-images.githubusercontent.com/26245512/51967398-e7318080-2477-11e9-8595-3fdda4f4eb90.png)
![screen shot 2019-01-30 at 10 14 33 am](https://user-images.githubusercontent.com/26245512/51967399-e7318080-2477-11e9-9773-e387b0ce4376.png)

Can you please provide me some more information?
The error log that you are getting, stuff like this.

Best,
Manu

**Comment by hbariki** [comment]
Thanks for the prompt reply. Sure, 
<img width="856" alt="screen shot 2019-01-30 at 9 00 42 am" src="https://user-images.githubusercontent.com/17537428/51998481-9d439d00-246d-11e9-8c23-9d6bb131d7b5.png">.
Above is the screenshot of the error where I can see in my Pagination.jsx file.

**Comment by einazare** [comment]
Hello again, @hbariki ,

Can you please also send the code of the pagination?
I mean how to you try to render it?
It seems to me that you have the `pages` prop undefined.

Best,
Manu

**Comment by hbariki** [comment]
Hello, 
Thanks for the response. I am just using pagination component as it is provided in the kit. Am I missing something because I have used the same for Buttons and card components.

**Comment by einazare** [comment]
Hello again, @hbariki ,

You are saying that you definitely have the pages prop defined where you render the Pagination?
Something like this:
```
    <Pagination
      pages={[
        { disabled: true, text: "Previous" },
        { text: 1 },
        { active: true, text: 2 },
        { text: 3 },
        { text: "Next" }
      ]}
    />
```

Best,
Manu

**Comment by hbariki** [comment]
Hi,
Thanks for the reply. I didn't pass the pages prop in the pagination where I render in my page. So got the above error. However, Just a one more quick question now I can render the pagination component. Now it looks like this
<img width="833" alt="screen shot 2019-01-31 at 10 22 51 am" src="https://user-images.githubusercontent.com/17537428/52075948-6f7c5800-2542-11e9-893d-57ee03f61569.png">

Just was wondering it displays me like the list items. How can I display the pagination like the above examples you have provided me.

**Comment by einazare** [comment]
Hello again, @hbariki ,

Have you included our styles inside your styles?
The styles for the Pagination component can be found here: https://demos.creative-tim.com/material-dashboard-pro-react/#/documentation/pagination

Best,
Manu

**Comment by hbariki** [comment]
Hi Again,

I have included the styles as above but accidentally replaced paginationStyle.jsx with parallaxStyle.jsx code. Now its working. Thanks for the help.
<img width="500" alt="screen shot 2019-02-01 at 9 07 08 am" src="https://user-images.githubusercontent.com/17537428/52137994-d2342900-2600-11e9-9b84-55b5b4948da3.png">
