### ISSUE TITLE
placeholder text is a bit off

### ISSUE THREAD

**Issue by hoangong** [creativetimofficial/ct-material-kit-pro-react#32]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting
placeholder text in text input is a bit off.

# Current Behavior
![screenshot 2019-02-19 at 01 32 33](https://user-images.githubusercontent.com/5703525/52984254-89dd7f00-33e6-11e9-8df9-bae5974c37b6.png)

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open any form (I just demonstrate in Contact Us form)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: iMac
* Operating System: Mac OS
* Browser and Version: Chrome latest version

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by einazare** [comment]
Hello there @1mdc ,

Thank you for your interest in working with our product.
Can you please tell us if you've done any changes to our product?
On our end, everything seems to be working as expected.

Best,
Manu
![screen shot 2019-02-19 at 9 16 18 am](https://user-images.githubusercontent.com/26245512/52996727-2162c200-3427-11e9-929f-2395b6ffae81.png)

**Comment by hoangong** [comment]
Hi,

No, I did not make any change to your product. I downloaded html version and run it in chrome incognito mode. 

I think the problem happens once I change iMac screen scale from default to Large.
Is there a way to make it display correctly in all scales?
<img width="686" alt="screenshot 2019-02-19 at 18 25 56" src="https://user-images.githubusercontent.com/5703525/53038121-d6bb6700-3473-11e9-8e60-da67125c58ac.png">

**Comment by einazare** [comment]
Hello again, @1mdc ,

So, is this an issue with the React product or the HTML product?
Can you please share with me the name of the archive you've downloaded?
Meanwhile, I will do some testing in the React product to see what is wrong.

Best,
Manu

**Comment by einazare** [comment]
Hello again @1mdc ,

On the React product, it seems to work normal.
<img width="1271" alt="screen shot 2019-02-20 at 9 50 07 am" src="https://user-images.githubusercontent.com/26245512/53075072-fd6db200-34f4-11e9-98af-450bdb1cd125.png">
If this is an issue with the HTML product, please open a ticket here: https://github.com/creativetimofficial/ct-material-kit-pro/issues

Best,
Manu

**Comment by hoangong** [comment]
Thanks for looking into this. 

I'm not sure how to replicate in another machine. I will close this for now. if my client reports this, I will re-open.
