### ISSUE TITLE
Rotating Cards are not responsive

### ISSUE THREAD

**Issue by rimoslav** [creativetimofficial/ct-material-kit-pro-react#34]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Rotating Cards should not cover each other, not even partially, on hover (on rotate) or when in normal state.

# Current Behavior

Depending on the window size, adjacent cards cover each other partially on some window sizes, and only on rotate on other window sizes. On large screen or mobile phone they work as expected (one card in a row on mobile)

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Reduce and enlarge screen size.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Dell Inspiron 15 3000
* Operating System: Windows 10
* Browser and Version: Google Chrome 73

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by einazare** [comment]
Hello there, @rimoslav ,

Thank you for your interest in working with our products.
I do not know how I haven't seen this issue earlier.
Can you please reproduce the issue inside a video?

Thank you,
Manu
