### ISSUE TITLE
Keep Getting Error Uncaught TypeError: Cannot read property 'list' of undefined

### ISSUE THREAD

**Issue by kholisrag** [creativetimofficial/ct-material-kit-pro-react#36]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

No More getting error `Uncaught TypeError: Cannot read property 'list' of undefined` , 

# Current Behavior

Keep Getting error `Uncaught TypeError: Cannot read property 'list' of undefined` in Chrome DevTools

# Failure Information (for bugs)

Uncaught TypeError: Cannot read property 'list' of undefined
    at App.render (App.jsx:40)
    at finishClassComponent (modules.js?hash=09de7f7f1fd51101225b5b3ebace03ec833f2b32:19056)
    at updateClassComponent (modules.js?hash=09de7f7f1fd51101225b5b3ebace03ec833f2b32:19011)
    at beginWork (modules.js?hash=09de7f7f1fd51101225b5b3ebace03ec833f2b32:19959)
    at performUnitOfWork (modules.js?hash=09de7f7f1fd51101225b5b3ebace03ec833f2b32:23627)
    at workLoop (modules.js?hash=09de7f7f1fd51101225b5b3ebace03ec833f2b32:23667)
    at HTMLUnknownElement.callCallback (modules.js?hash=09de7f7f1fd51101225b5b3ebace03ec833f2b32:4464)
    at Object.invokeGuardedCallbackDev (modules.js?hash=09de7f7f1fd51101225b5b3ebace03ec833f2b32:4514)
    at invokeGuardedCallback (modules.js?hash=09de7f7f1fd51101225b5b3ebace03ec833f2b32:4571)
    at replayUnitOfWork (modules.js?hash=09de7f7f1fd51101225b5b3ebace03ec833f2b32:22893)
## Steps to Reproduce

Here is the step : 

1. I code like this, in `App.jsx` :

```
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import { Meteor } from 'meteor/meteor';
import { Router, Route, Switch} from 'react-router';
import createBrowserHistory from 'history/createBrowserHistory';

// @material-ui/core components
import withStyles from "@material-ui/core/styles/withStyles";
import List from "@material-ui/core/List";
import ListItem from "@material-ui/core/ListItem";
// @material-ui/icons
import Search from "@material-ui/icons/Search";
import Email from "@material-ui/icons/Email";
import Face from "@material-ui/icons/Face";
import Settings from "@material-ui/icons/Settings";
import AccountCircle from "@material-ui/icons/AccountCircle";
import Explore from "@material-ui/icons/Explore";
// core components
import GridContainer from "/components/Grid/GridContainer.jsx";
import GridItem from "/components/Grid/GridItem.jsx";
import Header from "/components/Header/Header.jsx";
import CustomInput from "/components/CustomInput/CustomInput.jsx";
import CustomDropdown from "/components/CustomDropdown/CustomDropdown.jsx";
import Button from "/components/CustomButtons/Button.jsx";

import navbarsStyle from "/assets/jss/material-kit-pro-react/views/componentsSections/navbarsStyle.jsx";

class App extends Component {
  render() {

    const { classes } = this.props;
    const browserHistory = createBrowserHistory();

    return (
      <Router history={browserHistory}>
        <Header
          brand="Transparent"
          color="transparent"
          links={
            <List className={classes.list + " " + classes.mlAuto}>
              <ListItem className={classes.listItem}>
                <Button
                  color="transparent"
                  className={
                    classes.navLink + " " + classes.socialIconsButton
                  }
                >
                  <i
                    className={
                      classes.socialIcons +
                      " " +
                      classes.marginRight5 +
                      " fab fa-twitter"
                    }
                  />{" "}
                  Twitter
                </Button>
              </ListItem>
              <ListItem className={classes.listItem}>
                <Button
                  color="transparent"
                  className={
                    classes.navLink + " " + classes.socialIconsButton
                  }
                >
                  <i
                    className={
                      classes.socialIcons +
                      " " +
                      classes.marginRight5 +
                      " fab fa-facebook"
                    }
                  />{" "}
                  Facebook
                </Button>
              </ListItem>
              <ListItem className={classes.listItem}>
                <Button
                  color="transparent"
                  className={
                    classes.navLink + " " + classes.socialIconsButton
                  }
                >
                  <i
                    className={
                      classes.socialIcons +
                      " " +
                      classes.marginRight5 +
                      " fab fa-instagram"
                    }
                  />{" "}
                  Instagram
                </Button>
              </ListItem>
            </List>
          }
        />
      </Router>
    );
  }
}

export default App;

```

I confuse about the `{classes.list}` is defined?
can you guide me how you define it? or how to fix my issue?

## Context

* Device: darwin
* Operating System: macOS X
* Browser and Version: Chrome 73

**Comment by einazare** [comment]
Hello there, @petrukngantuk ,

Thank you for your interest in working with our products.
Sorry for this late response, since I am a Christian I've had some free days for the Easter Holiday:

- https://www.calendar-12.com/holidays/easter
- https://www.officeholidays.com/religious/orthodox/orthodox_easter.php

You need to export your component like this:
```
export default withStyles(navbarsStyle)(App);
```
You can take a look at all of our components, you will see that is our way of exporting them so that the styles are applied to the components.

All the best,
Manu
ReactJS Developer at Creative-Tim.com (http://creative-tim.com/)

Trying to help the open source community:

* https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618
* https://medium.freecodecamp.org/how-to-use-redux-in-reactjs-with-real-life-examples-687ab4441b85
* https://medium.freecodecamp.org/how-to-connect-a-react-design-system-with-firebase-and-redux-9646ca1c733f



* https://www.youtube.com/watch?v=raKV5Rb8oOM&list=PLWxSJr7LCl87rGlQtTo2PoX8hboUU0R8a
* https://www.youtube.com/watch?v=no2PD2kq-dE&list=PLWxSJr7LCl87OomktWFQVW30QDWtBqFlx



* https://www.udemy.com/learn-reactjs-with-webpack-4-babel-7-and-material-design/


If you've liked what you saw, help me with a comment, like, share or subscribe.
