### ISSUE TITLE
[Feature Request] Use relative paths for all imports

### ISSUE THREAD

**Issue by ericsolberg** [creativetimofficial/ct-material-kit-pro-react#42]
### What is your enhancement?
In my project, I've put all the Material Kit Pro React components and assets under their own directory, /src/muipro/components and /src/muipro/assets ... however this breaks all the links in Material UI to style sheets and component imports. They aren't too hard to global-search-and-replace, but then when there's an update I have to do it again. Thanks!

**Comment by einazare** [comment]
Hello again, @ericsolberg ,

I am very sorry about this, but the majority of our clients like better absolute paths, so we can't change this in any of our products.
As of the moment, about 1-5% of our customers have asked for relative ones. As you can see, at least 95% of our customers are happy with absolute ones.
To solve your issue, you could use the jsconfig.json file in which we set the src folder as the root folder. I am pretty sure you can add other folders as well, such as `src/muipro`.

Best,
Manu

**Comment by sakhmedbayev** [comment]
Using absolute paths is NOT a good idea as it breaks IDE support - VSCode cannot navigate to absolute pathed files on `Command + click`

**Comment by einazare** [comment]
Hello there, @sakhmedbayev ,

Is this link useful to you: https://medium.com/@fpastorelima/using-absolute-imports-with-vscode-and-create-react-app-dec6ba0da7ed

Best,
Manu

**Comment by sakhmedbayev** [comment]
In case someone is struggling to make it work with Gatsby.js

```
{
      resolve: "gatsby-plugin-root-import",
      options: {
        src: path.join(__dirname, "src"),
        components: path.join(__dirname, "src/components"),
        assets: path.join(__dirname, "src/assets")
      }
    },
```
and for VSCode to be able to navigate properly to the definitions, change jsconfig.json in the following way:

```
{
  "compilerOptions": {
    "baseUrl": "src",
    "paths": {
      "components": ["src/components"],
      "assets": ["src/assets"]
    }
  }
}
```
