### ISSUE TITLE
[Bug] unable to compile components with webpack

### ISSUE THREAD

**Issue by garygz** [creativetimofficial/ct-material-kit-pro-react#43]
### Version
1.7.0
### Reproduction link
http://dev-issue.com
### Operating System
MacOs
### Device
Mac
### Browser & Version
Chrome (latest)
### Steps to reproduce
webpack 4.35.2, material-ui: 0.20.2
1. imported components into an existing react app
2. in the index.js created a route taken from the sample to point to AboutUsPage
3. It fails to render because withStyles returns an object not an expected class
### What is expected?
no errors
### What is actually happening?
  }
checkPropTypes.js?a15c:20 Warning: Failed prop type: Invalid prop `component` of type `object` supplied to `Route`, expected `function`.
    in Route
printWarning @ checkPropTypes.js?a15c:20
checkPropTypes @ checkPropTypes.js?a15c:82
validatePropTypes @ react.development.js?72d0:1666
createElementWithValidation @ react.development.js?72d0:1755
(anonymous) @ index.js?75f5:26
./client/app/index.js @ app.js:2770
__webpack_require__ @ app.js:724
fn @ app.js:101
0 @ app.js:11823
__webpack_require__ @ app.js:724
(anonymous) @ app.js:791
(anonymous) @ app.js:794
tiny-invariant.esm.js?f51f:11 Uncaught Error: Invariant failed: You should not use <Link> outside a <Router>
    at invariant (tiny-invariant.esm.js?f51f:11)
    at eval (react-router-dom.js?e792:154)
    at updateContextConsumer (react-dom.development.js?61bb:15484)
    at beginWork (react-dom.development.js?61bb:15672)
    at performUnitOfWork (react-dom.development.js?61bb:19312)
    at workLoop (react-dom.development.js?61bb:19352)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:199)
    at invokeGuardedCallback (react-dom.development.js?61bb:256)
    at replayUnitOfWork (react-dom.development.js?61bb:18578)
invariant @ tiny-invariant.esm.js?f51f:11
(anonymous) @ react-router-dom.js?e792:154
updateContextConsumer @ react-dom.development.js?61bb:15484
beginWork @ react-dom.development.js?61bb:15672
performUnitOfWork @ react-dom.development.js?61bb:19312
workLoop @ react-dom.development.js?61bb:19352
callCallback @ react-dom.development.js?61bb:149
invokeGuardedCallbackDev @ react-dom.development.js?61bb:199
invokeGuardedCallback @ react-dom.development.js?61bb:256
replayUnitOfWork @ react-dom.development.js?61bb:18578
renderRoot @ react-dom.development.js?61bb:19468
performWorkOnRoot @ react-dom.development.js?61bb:20342
performWork @ react-dom.development.js?61bb:20254
performSyncWork @ react-dom.development.js?61bb:20228
requestWork @ react-dom.development.js?61bb:20097
scheduleWork @ react-dom.development.js?61bb:19911
scheduleRootUpdate @ react-dom.development.js?61bb:20572
updateContainerAtExpirationTime @ react-dom.development.js?61bb:20600
updateContainer @ react-dom.development.js?61bb:20657
ReactRoot.render @ react-dom.development.js?61bb:20953
(anonymous) @ react-dom.development.js?61bb:21090
unbatchedUpdates @ react-dom.development.js?61bb:20459
legacyRenderSubtreeIntoContainer @ react-dom.development.js?61bb:21086
render @ react-dom.development.js?61bb:21155
(anonymous) @ index.js?75f5:22
./client/app/index.js @ app.js:2770
__webpack_require__ @ app.js:724
fn @ app.js:101
0 @ app.js:11823
__webpack_require__ @ app.js:724
(anonymous) @ app.js:791
(anonymous) @ app.js:794
Show 2 more frames
react-dom.development.js?61bb:17117 The above error occurred in the <Context.Consumer> component:
    in Link (created by Header)
    in span (created by ForwardRef(Button))
    in button (created by ForwardRef(ButtonBase))
    in ForwardRef(ButtonBase) (created by WithStyles(ForwardRef(ButtonBase)))
    in WithStyles(ForwardRef(ButtonBase)) (created by ForwardRef(Button))
    in ForwardRef(Button) (created by WithStyles(ForwardRef(Button)))
    in WithStyles(ForwardRef(Button)) (created by Header)
    in div (created by ForwardRef(Toolbar))
    in ForwardRef(Toolbar) (created by WithStyles(ForwardRef(Toolbar)))
    in WithStyles(ForwardRef(Toolbar)) (created by Header)
    in header (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by ForwardRef(AppBar))
    in ForwardRef(AppBar) (created by WithStyles(ForwardRef(AppBar)))
    in WithStyles(ForwardRef(AppBar)) (created by Header)
    in Header (created by WithStyles(Header))
    in WithStyles(Header) (created by AboutUsPage)
    in div (created by AboutUsPage)
    in AboutUsPage (created by WithStyles(AboutUsPage))
    in WithStyles(AboutUsPage) (created by Route)
    in Route
    in Switch
    in Router

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

---

**Comment by einazare** [comment]
Hello there, @garygz ,

Thank you for your interest in working with our products.
Please follow this tutorial here: https://medium.com/free-code-camp/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618

Best,
Manu
