### ISSUE TITLE
[Bug] Not able to Load the theme in IE 11

### ISSUE THREAD

**Issue by manuterawe** [creativetimofficial/ct-material-kit-pro-react#45]
### Version
1
### Reproduction link
https://demos.creative-tim.com/material-kit-pro-react/#/components
### Operating System
windows 
### Device
desktop
### Browser & Version
IE11
### Steps to reproduce
open the theme in IE 11
### What is expected?
Want to work theme in IE11 and below 
### What is actually happening?
getting a blank screen IE browsers. But working fine in IE Edge 

---

**Comment by einazare** [comment]
Hello there, @manuterawe ,

Thank you for your interest in working with our products.
Please read our README here: https://github.com/creativetimofficial/ct-material-kit-pro-react

Best,
Manu

**Comment by manuterawe** [comment]
want to confirm will it  work only latest versions of IE Edge will not support  internet explorer 11 ?

**Comment by einazare** [comment]
Hello again, @manuterawe ,

As per our README, we only offer support for the following:
<img src="https://s3.amazonaws.com/creativetim_bucket/github/browser/chrome.png" width="64" height="64"> <img src="https://s3.amazonaws.com/creativetim_bucket/github/browser/firefox.png" width="64" height="64"> <img src="https://s3.amazonaws.com/creativetim_bucket/github/browser/edge.png" width="64" height="64"> <img src="https://s3.amazonaws.com/creativetim_bucket/github/browser/safari.png" width="64" height="64"> <img src="https://s3.amazonaws.com/creativetim_bucket/github/browser/opera.png" width="64" height="64">
We are not offering support for Internet Explorer - all the major companies are dropping IE support.

Best,
Manu
