### ISSUE TITLE
[Bug] Styles example overrides link is broken(https://material-ui.com/customization/overrides/#overriding-with-class-names?ref=creativetim)

### ISSUE THREAD

**Issue by ekhaidarov** [creativetimofficial/ct-material-kit-pro-react#46]
### Version
Latest 1.7.0
### Reproduction link
https://material-ui.com/customization/overrides/#overriding-with-class-names?ref=creativetim
### Operating System
Mac OS X 
### Device
desktop
### Browser & Version
Chrome
### Steps to reproduce
Unable to open examples (https://material-ui.com/customization/overrides/#overriding-with-class-names?ref=creativetim) link from the documentation : https://demos.creative-tim.com/material-kit-pro-react/#/documentation/styles
### What is expected?
Being able to see and how components could be styled through an example
### What is actually happening?
Page Not Found

---

**Comment by einazare** [comment]
Hello there, @ekhaidarov ,

Thank you for your interest in working with our products and sorry for this inconvenience.
It seems that Material-UI has dropped that link.
We are going to change that link with these ones:

- https://material-ui.com/styles/advanced/#class-names
- https://material-ui.com/styles/advanced/#withstyles

Hope this helps.

Best,
Manu

**Comment by ekhaidarov** [comment]
Thanks for the reply, Manu. These are very generic examples, looking through the mkit-pro code I could not figure out a way to simply provide brand overrides for primary, secondary colors. After some digging, I also realized that there is also bootstrap being used for third party components, which could be defined the brand file after adding custom colors, but it is not straight forward. 

Any guidance here that could simplify working with branded colors would much be appreciated.

Thanks,
Eradj

**Comment by ekhaidarov** [comment]
Just one last comment, I was under the impression that m-kit-pro would be able to utilize themes, and I could override the colors through the theme, but that also didn't work.

**Comment by einazare** [comment]
Hello again, Eradj,

Is this link helpful: https://demos.creative-tim.com/material-kit-pro-react/#/documentation/styles
No, we do not use the theme provider of Material-UI since we have a lot of custom css, which can only be achieved by using the jss with the withStyles function. It would have been a lot harder to understand our code with both withStyles and the theme provider. For the moment we'll leave it like so, in our next update which is set for the next Friday, we'll change our components to use the makeStyles function, which is a React Hook. But besides that, we are not going to add the theme provider as of the moment.

Best,
Manu

**Comment by ekhaidarov** [comment]
Hi Manu, 

Thanks for the quick replies on this. I have gone through the styling docs to draw correlation to the 
m-kit pro approach. Am I correct to understand that besides modifying "material-kit-pro-react.jsx" directly there is no way to provide brand overrides? I am just trying to set the direction for the designer. Thanks again. 

Regards, 
Eradj

**Comment by einazare** [comment]
Hello again, Eradj,

Sorry for this late reply. I've been on a small vacation thanks to the Assumption SOLEMNITY celebration of the Catholic and Orthodox faiths (http://www.romcal.net/output/2019.htm).
There are some components that make use of scss, and for those, the branding colors are found inside: `src/assets/scss/core/_variables.scss`.
You can check on our live docs which components are using jss, and which are using scss: https://demos.creative-tim.com/material-kit-pro-react/#/documentation/tutorial

Best, 
Manu
