### ISSUE TITLE
[Bug] Select menu Items larger that maxHeight menu box are not displayed  on iphone and ipad devices

### ISSUE THREAD

**Issue by mms197** [creativetimofficial/ct-material-kit-pro-react#49]
### Version
1.8.0
### Operating System
ios
### Device
iphone and ipad
### Browser & Version
chrome and safari
### Steps to reproduce
- Open multiple select (9 cities are provisioned as menu items) 
['Madrid', 'Rome', 'Lisbon', 'Paris', 'London', 'Amsterdam', 'Berlin', 'Helsinki', 'Oslo']

- The 5 cities that fit into the maxHeight menu box are displayed
['Madrid', 'Rome', 'Lisbon', 'Paris', 'London']

- Try to scroll to see the remaining 4 cites

- The remaining 4 cities are not displayed on iphone and ipad until you tap the items
(it works as expected on desktop and android mobile devices)

### What is expected?
all menu items can be scrolled and selected normally as in desktop and android
### What is actually happening?
I dont know but looks to be a function of iphone and ipad so ios

---

**Comment by einazare** [comment]
Hello there, @mms197 ,

Thank you for providing us with this bug.
At the moment we do not have a solution for this. 
Maybe you are right, and it is something only on iOS?
I will continue to find a solution for it.

Best,
Manu

**Comment by mms197** [comment]
Thanks Manu! Would love to see a fix for this as my app relies heavily on selects with large menu items ;-)

**Comment by mms197** [comment]
Hi there Manu, do you know when a fix can be available or alternatively some advice how to work around it ?

Thanks! Martin

**Comment by einazare** [comment]
Hello again, @mms197 ,

At the moment I haven't found the solution.
I will look again in our next update, which is set somewhere in December.

Best,
Manu
