### ISSUE TITLE
[Bug] TypeError on build

### ISSUE THREAD

**Issue by ghost** [creativetimofficial/ct-material-kit-pro-react#51]
### Version
whatever most recent download was
### Reproduction link
http://www.google.com
### Operating System
All
### Device
All
### Browser & Version
N/A
### Steps to reproduce
1. Download and unzip the product
2. Follow instructions at: https://demos.creative-tim.com/material-kit-pro-react/#/documentation/tutorial

### What is expected?
localhost to open up the sample to play around with
### What is actually happening?
immediate compile error:

```
./src/components/Card/Card.js
TypeError: Cannot read property 'type' of undefined
Occurred while linting /Users/sethmartin/Projects/pc_sandbox/material-kit-pro-react-v1.8.0/src/components/Card/Card.js:16
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)
```

---
### Solution
https://github.com/facebook/create-react-app/issues/7753
To solve the issue, please run the following: npm i -E eslint@6.4.0.
--> Thanks @EINazare

**Comment by einazare** [comment]
Hello there, @sethgoodluck ,

Is this still an issue? 
I can see that you have added a solution, does everything work now?

Best,
Manu

**Comment by Sh4reef** [comment]
@EINazare Same issue occurred with me, I tried using `npm install:clean` still getting the error

```
./src/layouts/Admin.js
TypeError: Cannot read property 'type' of undefined
Occurred while linting /Users/ahmadbanjar/Desktop/PROA-webapp-material-ui/src/layouts/Admin.js:26
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)
```

**Comment by einazare** [comment]
Hello there, @sethgoodluck , @Sh4reef  ,

Thank you for your interest in working with our products.
This is actually an error from the react-scripts package, here is the link to the mentioned issue: https://github.com/facebook/create-react-app/issues/7753
To solve the issue, please run the following: `npm i -E eslint@6.4.0`.

Best,
Manu

**Comment by ghost** [comment]
@EINazare - Out of curiosity, do you know why this is happening for the material kit but not some of the other kits (like Paper Kit?)

**Comment by einazare** [comment]
Hello again, @sethgoodluck ,

It is because of the react-scripts version inside the package.json.
The Paper Kit product comes with an older one, which auto-install eslint v6.40, or an older one, so you do not have the issue from the eslint version 6.5.0, which comes with the react-scripts version found inside the Material products.

Best,
Manu

**Comment by ghost** [comment]
This makes sense. The issue is closed for me for now. 
Feel free to close it if you'd like and thank you for the rapid response - really appreciate it

**Comment by einazare** [comment]
I will leave it open, and on my next update I will see if the newer react-scripts will solve this issue out of the box, or I will need to add inside our package.json the eslint version 6.4.0.
