### ISSUE TITLE
[Bug] How to Upgrade of code started building with Metarial-kit now bought Material-react-Pro

### ISSUE THREAD

**Issue by RichardDrent** [creativetimofficial/ct-material-kit-pro-react#53]
### Version
1 day old
### Reproduction link
https://jsfiddle.net/
### Operating System
Ubuntu 19.04
### Device
laptop
### Browser & Version
chrome
### Steps to reproduce
1. I start building a react project with Material UI kit
2. liked the product
3. go to https://www.creative-tim.com/templates/material-ui buy a bundle
4. hope there is a readme saying do this do that to upgrade...... :(
5. call for help 
### What is expected?
that my project startes again, without rebuilding the project page by page
### What is actually happening?
Ugly errors

/src/assets/scss/material-kit-pro-react.scss?v=1.8.0 (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-4!./src/assets/scss/material-kit-pro-react.scss?v=1.8.0)
@import "node_modules/react-image-gallery/styles/scss/image-gallery.scss";
^
      File to import not found or unreadable: node_modules/react-image-gallery/styles/scss/image-gallery.scss.
      in /home/richard/HelloOpticalUI/src/assets/scss/plugins/_plugin-react-image-gallery.scss (line 1, column 1)

---
### Solution
hoping you have one :)
### Additional comments
probably this is a stupid question, but just started building in react for the first time after 15 years of asp.net. everything is new 

cheers richard

**Comment by einazare** [comment]
Hello there, Richard,

Thank you for your interest in working with our products.
Can you please share me the links for these:
- Metarial-kit
- Material-react-Pro

Best,
Manu

**Comment by RichardDrent** [comment]
Let it be as it is, I rebuild my project over

Richard
