### ISSUE TITLE
[Bug] dom-helpers dependency clash

### ISSUE THREAD

**Issue by rossoha** [creativetimofficial/ct-material-kit-pro-react#56]
### Version
1.8.0
### Reproduction link
https://github.com/oliviertassinari/react-swipeable-views/issues/542
### Operating System
Any
### Device
Any
### Browser & Version
Any
### Steps to reproduce
yarn why dom-helpers                            
yarn why v1.21.1
[1/4] 🤔  Why do we have the module "dom-helpers"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "dom-helpers@3.4.0"
info Reasons this module exists
   - "react-swipeable-views" depends on it
   - Hoisted from "react-swipeable-views#dom-helpers"
info Disk size without dependencies: "212KB"
info Disk size with unique dependencies: "852KB"
info Disk size with transitive dependencies: "892KB"
info Number of shared dependencies: 2
=> Found "react-transition-group#dom-helpers@5.1.3"
info This module exists because "@material-ui#core#react-transition-group" depends on it.
info Disk size without dependencies: "980KB"
info Disk size with unique dependencies: "3.17MB"
info Disk size with transitive dependencies: "3.21MB"
info Number of shared dependencies: 3
✨  Done in 0.58s.

### What is expected?
I expect libraries:
"@material-ui/core" : "4.3.2"
"react-swipeable-views" : "0.13.3"
to be aligned in a way when they will be using the same major version of dom-helpers
### What is actually happening?
I'm having exception:
Module not found: Error: Can't resolve 'dom-helpers/removeClass'  in 'node_modules/react-transition-group/esm'
Because: https://github.com/oliviertassinari/react-swipeable-views/issues/542

---

**Comment by einazare** [comment]
Hello there, @rossoha ,

Please download again the product, and run the following:
`npm install`
After that
`npm start`

Let me know if you still have the issue.
I can see that you have used `yarn`, but we do not offer support for it, we only use `npm`.

Best,
Manu
