### ISSUE TITLE
Connecting my app

### ISSUE THREAD

**Issue by obaidy** [creativetimofficial/ct-material-kit-pro-react#57]
i purchase material kit pro react and i would like to ask what is the best way to connect the contact form to backend like firebase, netlify, .. etc and do you have examples of how  to?

**Comment by einazare** [comment]
Hello there, @obaidy ,

Thank you for your interest in working with our products.
Sorry for this late response, we’ve been on a small Christmas Vacation.
Check our tutorial here: https://www.youtube.com/watch?v=BMPHfnAA9iI&list=PLWxSJr7LCl87rxd7A4j9WEFUbJz4gTNLa

Best,
Manu
