### ISSUE TITLE
[Bug] Where is JSX files

### ISSUE THREAD

**Issue by sakhmedbayev** [creativetimofficial/ct-material-kit-pro-react#58]
### Version
1.8.0
### Reproduction link
https://demos.creative-tim.com/material-kit-pro-react/#/documentation/typography
### Operating System
iOS
### Device
mac
### Browser & Version
latest
### Steps to reproduce
go here https://demos.creative-tim.com/material-kit-pro-react/#/documentation/typography
 
read this text 

Styles
You will find the styles for these components in
src/assets/jss/material-kit-pro-react/components/typographyStyle.jsx

try to find this file in the codebase
### What is expected?
typographyStyle.jsx file to be found
### What is actually happening?
there is typographyStyle.js file

---

**Comment by einazare** [comment]
Hello there, @sakhmedbayev ,

Thank you for your interest in working with our products.
We've changed all the files from jsx to js in this product.
It seems that we haven't changed those inside our live docs, we'll make the changes in a few days.

Best,
Manu
