### ISSUE TITLE
CustomDropdown Usage?

### ISSUE THREAD

**Issue by acmitch** [creativetimofficial/ct-material-kit-pro-react#6]
Trying to use the CustomDropdown with links or any sort of data other than plaintext, however, nothing seems to layout well, due to everything being wrapped in a MenuItem. What's the point of this component if you can't tie into the onclick logic?

In the example below the link doesn't fill the entire menu item, there you have to click on the exact text.

```js
<CustomDropdown
                caret={false}
                dropdownHeader="User Actions"
                buttonText={
                  <Avatar
                    alt="Adelle Charles"
                    src={avatarImg}
                  />
                }
                buttonProps={{
                  color: "transparent",
                  style: {padding: 5},
                }}
                dropdownList={[
                  "Sign Out",
                  <Link to="/test" className={classes.dropDownLink}>Sign Out</Link>
                ]}
              />
```

**Comment by einazare** [comment]
Hello @acmitch ,

And thank you for your interest in using our product.
For this issue you can do what we have done in our `HeaderLinks` component.
As you can see in our product, either on the live demo, either on your own downloaded product, the links inside the dropdowns from our navbar works just as expected.
Just navigate inside `src/components/Header/HeaderLinks.jsx` and take a look for example at the `CustomDropdown` that starts at `line 90` and ends at `line 111`.

Hope this information helps you.

Best,
Manu

**Comment by acmitch** [comment]
@EINazare thanks a lot. Exactly what I needed.
