### ISSUE TITLE
[Bug] fa icons aren't loading

### ISSUE THREAD

**Issue by tlester** [creativetimofficial/ct-material-kit-pro-react#62]
### Version
1.8.0
### Reproduction link
https://gist.github.com/tlester/a631ef1b1d5a2acd02a5c5e4f6c4d3a6
### Operating System
catalina
### Device
mbp
### Browser & Version
Chrome and Safari latest
### Steps to reproduce
This is likely my ignorance to the package.   I had an existing project that I have then laid in the Material Kit Pro React code on to.   Everything works fine, but the "fa" icons, like "fa-twitter" are not displaying.   

Like:

                        <Button justIcon round color="twitter">
                          <i className={classes.socials + " fab fa-twitter"} />
                        </Button
### What is expected?
twitter icon (or any other fa icon) shows up when I use them as an argument to "className". 
### What is actually happening?
They are not showing up.  

---

**Comment by einazare** [comment]
Hello there, @tlester ,

Have you added the font-awesome CSS to your project as well?
You need to add the following HTML code inside your index.html (inside the head tags):
```
<!--     Fonts and icons     -->
    <link
      rel="stylesheet"
      type="text/css"
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons"
    />
    <link
      href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
      rel="stylesheet"
    />
```
Check it our how we've done it inside our project under `public/index.html`.

Best,
Manu
