### ISSUE TITLE
[Feature Request] Rotating Card on click or tap

### ISSUE THREAD

**Issue by alejandroeclair** [creativetimofficial/ct-material-kit-pro-react#65]
### What is your enhancement?
Rotating cards in material-react do not have the props/feature to make it rotatable on click of the card, or on a button, like in this guide:
https://demos.creative-tim.com/bs3/material-kit-pro/tutorial-components.html

**Comment by einazare** [comment]
Hello there, @alejandroeclair ,

We have the requested components here: https://demos.creative-tim.com/material-kit-pro-react/#/components#morphingCards
Please check the `src/views/ComponentsPage/Sections/SectionCards.js` file for more info.

We'll add a sample code inside our live preview as well.

Best,
Manu

**Comment by alejandroeclair** [comment]
Perfect, thanks so much @EINazare !

**Comment by einazare** [comment]
We'll leave the issue opened until we'll add the sample code into our live docs as well.

**Comment by sajadevo** [comment]
**Hi there**,

We've just updated the product to v2.0.0 and now its coming with a totally new structure, fresh design and new look.

**All the best**
**Sajad**
