### ISSUE TITLE
[Bug] Rotating Cards in NavPills can not autofix height

### ISSUE THREAD

**Issue by clwater** [creativetimofficial/ct-material-kit-pro-react#71]
### Version
v1.9
### Reproduction link
https://jsfiddle.net/
### Operating System
Mac
### Device
PC
### Browser & Version
Version 86.0.4240.111 (Official Build) (x86_64)
### Steps to reproduce
Create a NavPills,
add Rotating Cards in one of the NavPills
### What is expected?
when the Rotating Cards tab is show, NavPills height can not  auto fix,  
### What is actually happening?
when the Rotating Cards tab is show, NavPills height can auto fix,  

---

**Comment by einazare** [comment]
Hello again, @clwater ,

We've tested your issue, and the behavior is as expected.
If you need a static height for the NavPills please check my other comment here: https://github.com/creativetimofficial/ct-material-kit-pro-react/issues/68#issuecomment-716356736

Please note that there is not CSS/JSS/SCSS rule that could create the behavior that you are trying to achieve.

Best,
Manu
