### ISSUE TITLE
[Feature Request] Increase Text Contrast for Documentation Page

### ISSUE THREAD

**Issue by DeepakKapiswe** [creativetimofficial/ct-material-kit-pro-react#73]
### What is your enhancement?
Hello Team,
Thanks for the nice template, although I'm facing issues reading the documentation page. It would have been better and more reader friendly if there was more text contrast present on the doc page.
Hope you will find this helpful and plan to modify the appearance.
Thanks

**Comment by sajadevo** [comment]
**Hi there**,

We've just updated the product to v2.0.0 and now its coming with a totally new structure, fresh design and new look.

**All the best**
**Sajad**
