### ISSUE TITLE
[Feature Request] Create form with Submit Function 

### ISSUE THREAD

**Issue by kenchan13** [creativetimofficial/ct-material-kit-pro-react#75]
### What is your enhancement?
Hi! I need to create a form with submit function.
I read material-kit & material-ui doc, and i cannot find solution.

Something like that
https://codepen.io/kenchan13/pen/OJRKByb?editors=0010
I need this feature to implement From 
Thanks!

**Comment by einazare** [comment]
Hello there, @kenchan13 ,

Unfortunately, we are not doing client-based applications.
Please check our customer support details here: https://www.creative-tim.com/support-terms

If you need custom development, please refer to this page here: https://services.creative-tim.com/?ref=ct-footer

Best,
Manu
