### ISSUE TITLE
Missing upgrading tutorial in documentation

### ISSUE THREAD

**Issue by lukaszswitaj** [creativetimofficial/ct-material-kit-pro-react#8]
# Prerequisites

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

The documentation should contain an upgrade guide of application to the latest version of the Material Kit Pro React

# Current Behavior

The documentation is missing.

# Failure Information (for bugs)

Not applicable.

## Steps to Reproduce

Let's try to have working application and want to upgrade it :)

## Context

Not applicable.

## Failure Logs

Not applicable

**Comment by einazare** [comment]
Hello @lukaszswitaj ,

And thank you for your interest in using our product.
Can you please provide a tutorial on how you should update this product so we can know how to make one?
We've always believed that the [CHANGELOG.md](https://github.com/creativetimofficial/ct-material-kit-pro-react/blob/master/CHANGELOG.md) should be enough for this.

Best,
Manu

**Comment by lukaszswitaj** [comment]
Thank you for reply, @EINazare ,

I would like to know that myself ;)

The thing is, I'm not sure how to make the correct upgrade. I do not know which files to overwrite, which subdirectories to replace, which NPM commands to call in the console, etc.

Of course, in theory, I can make a copy of my project and try to make it work.

As the creator, you are the only people who know how to perform a full correct upgrade of an existing project. I assure you that if I was a more experienced programmer, I would be tempted to publish such tutorial.

Regards
Łukasz

**Comment by einazare** [comment]
Hello again @lukaszswitaj ,

We are going to think of something and try to make a tutorial for this.
Not sure how, since every of our clients have their own projects, and we can't figure out a way to generalize such tutorial.
Maybe make our CHANGELOG a bit more specific.
Anyway, we are going to think of something.

Best,
Manu

**Comment by lukaszswitaj** [comment]
Thank you @EINazare

**Comment by einazare** [comment]
Hello there, @lukaszswitaj ,

We've devised a way to make updates of our products.
The easiest way to make updates is as follows:

* You create two repositories on a versioning control system (for example GitHub, GitLab, Bitbucket etc.)  - if it's a PRO paid product, we suggest that the repositories to be private
* On the first repository, you add our product unaltered
* On the second repository, you add our product and/or develop your project
* Each time we release a new version of the product at hand, you download again the product, and put it on top of the first repository, the versioning control system (for example GitHub, GitLab, Bitbucket etc.) will tell you all the differences between the versions
* By using a repository, you can even make new branches for each of our new version, that way, you will always have all the versions

Hope this information is of help. If you have further questions, let us know.

Best,
Manu
ReactJS Developer @Creative-Tim.com
