### ISSUE TITLE
[Bug] Update google maps api to remove context legacy warning

### ISSUE THREAD

**Issue by rickstaa** [creativetimofficial/ct-material-kit-pro-react#80]
### Version
1.9.0 
### Reproduction link
https://demos.creative-tim.com/material-kit-pro-react/#/contact-us
### Operating System
Ubuntu 20.04, windows 10
### Device
Hp Zbook G5
### Browser & Version
Chrome v8.0.4324.150, firefox v85.0.1
### Steps to reproduce
1. Go to [the contact-us page](https://demos.creative-tim.com/material-kit-pro-react/#/components)
2. Open the console.
3. See react Legacy Context deprecation warning.

### What is expected?
There should be no warning.
### What is actually happening?
The warning is visible.

---
### Solution

This can be fixed by moving over to the new Maintained version of the google-react-maps API (see https://www.npmjs.com/package/@react-google-maps/api). The new code is as follows (Add your API key to the .even file).

```javascript
....
const CustomMap = (
  <LoadScript googleMapsApiKey={process.env.REACT_APP_GOOGLE_MAPS_API_KEY}>
    <GoogleMap
      zoom={8}
      center={{
        lat: 52.449,
        lng: 4.17,
      }}
      streetViewControl={false}
      options={{
        streetViewControl: false,
        mapTypeControl: false,
        zoomControl: false,
        fullscreenControl: false,
        backgroundColor: "#17263c",
        ...googleMapsStyle["dark"],
      }}
      mapContainerStyle={{
        height: "100%",
        overflow: "hidden",
      }}
    >
      <Marker
        position={{ lat: 52.38149641351333, lng: 4.635444167817593 }}
        animation="2"
      />
    </GoogleMap>
  </LoadScript>
);
...
<div className={classes.bigMap}>{CustomMap}</div>
...

```

**Comment by einazare** [comment]
Hello there, @rickstaa ,

Thank you for your issue and solution.
Actually, in our next update, we'll replace the `react-google-maps` components with the simple Google Maps API - i.e. pure JavaScript, or, we'll replace it with `https://www.npmjs.com/package/@googlemaps/js-api-loader`.

Best,
Manu

**Comment by rickstaa** [comment]
@EINazare Great! I wasn't aware that the package looks good, fewer dependencies and closer to the actual API! It works a lot better than the react component.
