### ISSUE TITLE
[Bug] Material Kit PRO React will not install, will not run

### ISSUE THREAD

**Issue by jessicagallagher** [creativetimofficial/ct-material-kit-pro-react#82]
### Version
1.9.0
### Reproduction link
https://demos.creative-tim.com/material-kit-pro-react/?_ga=2.126034509.1101420317.1616676140-1212158183.1616676140#/documentation/tutorial
### Operating System
Big Sur 11.2.2
### Device
MacBook Pro
### Browser & Version
Google Chrome Version 89.0.4389.90 (Official Build) (x86_64)
### Steps to reproduce
1. npm install --> throws pages of errors
2. npm run install:clean --> this isn't even a command
3. NODE_PATH=./src --> throws pages of errors
4. npm install --g cross-env --> change start to: "start": "NODE_PATH=./src react-scripts start", --> throws pages of errors
5. npm install --force --> cannot resolve dependencies, throws pages of errors

### What is expected?
I purchased this entire full-stack bundle and it doesn't work. It won't run. I can't actually use this product and likely the entire bundle, and I'm about to dispute the charge on my credit card. The documentation provided isn't helpful or thorough and you're using dependencies that haven't been updated in over a year. I've also tried copying and pasting specific components, manually editing them / css, and installing any dependencies the components need, and I still get the same errors. 
### What is actually happening?
Ironically, when I post my error logs here, it won't let me submit the issue.

---
### Additional comments
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: @babel/core@7.9.0
npm ERR! node_modules/@babel/core
npm ERR!   @babel/core@"7.9.0" from react-scripts@3.4.1
npm ERR!   node_modules/react-scripts
npm ERR!     react-scripts@"3.4.1" from the root project
npm ERR!   @babel/core@"^7.4.5" from @svgr/webpack@4.3.3
npm ERR!   node_modules/@svgr/webpack
npm ERR!     @svgr/webpack@"4.3.3" from react-scripts@3.4.1
npm ERR!     node_modules/react-scripts
npm ERR!       react-scripts@"3.4.1" from the root project
npm ERR!   9 more (babel-jest, babel-loader, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @babel/core@"^7.13.0" from @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.13.12
npm ERR! node_modules/@babel/preset-env/node_modules/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining
npm ERR!   @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@"^7.13.12" from @babel/preset-env@7.13.12
npm ERR!   node_modules/@babel/preset-env
npm ERR!     @babel/preset-env@"^7.4.5" from @svgr/webpack@4.3.3
npm ERR!     node_modules/@svgr/webpack
npm ERR!       @svgr/webpack@"4.3.3" from react-scripts@3.4.1
npm ERR!       node_modules/react-scripts
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/jessicagallagher/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jessicagallagher/.npm/_logs/2021-03-27T12_28_38_502Z-debug.log
➜  material-kit-pro-react-v1.9.0 git:(main) ✗ npm install --g cross-env

added 7 packages, and audited 8 packages in 1s

found 0 vulnerabilities
➜  material-kit-pro-react-v1.9.0 git:(main) ✗ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: @babel/core@7.9.0
npm ERR! node_modules/@babel/core
npm ERR!   @babel/core@"7.9.0" from react-scripts@3.4.1
npm ERR!   node_modules/react-scripts
npm ERR!     react-scripts@"3.4.1" from the root project
npm ERR!   @babel/core@"^7.4.5" from @svgr/webpack@4.3.3
npm ERR!   node_modules/@svgr/webpack
npm ERR!     @svgr/webpack@"4.3.3" from react-scripts@3.4.1
npm ERR!     node_modules/react-scripts
npm ERR!       react-scripts@"3.4.1" from the root project
npm ERR!   9 more (babel-jest, babel-loader, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @babel/core@"^7.13.0" from @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.13.12
npm ERR! node_modules/@babel/preset-env/node_modules/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining
npm ERR!   @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@"^7.13.12" from @babel/preset-env@7.13.12
npm ERR!   node_modules/@babel/preset-env
npm ERR!     @babel/preset-env@"^7.4.5" from @svgr/webpack@4.3.3
npm ERR!

**Comment by ambupilot** [comment]
Same issue here...
The 'free demo' version worked as it should be.
Then I decided to buy the PRO version, and this won't let me install at all. Could not resolve dependencies.

**Comment by ambupilot** [comment]
**UPDATE on my previous reply**: it seems like my Node version was too new :-/
- Downgraded from 15 -> 14.16.0

Still some depreciation warnings, but localhost:3000 shows the prebuild pages.
I hope this helps you (partially).

Regards,
Martijn

**Comment by jessicagallagher** [comment]
Thanks @ambupilot — should've done more due diligence I guess. Just now seeing on their website that all of their reviews are basically the same: great, design.

**Comment by einazare** [comment]
Hello there, guys,

Our React products only work with NodeJS LTS version due to our dependencies - if I remember correctly, it is mainly because of node-sass, which only works with NodeJS LTS version.
We'll add this warning in our Material docs as well.

Best,
Manu

**Comment by jessicagallagher** [comment]
That would've been incredibly helpful to know before I spent actual money on this.

**Comment by starkajs** [comment]
> Hello there, guys,
> 
> Our React products only work with NodeJS LTS version due to our dependencies - if I remember correctly, it is mainly because of node-sass, which only works with NodeJS LTS version.
> We'll add this warning in our Material docs as well.
> 
> Best,
> Manu

I'm using latest version of NodeLTS and still getting the same. Paid for the PRO bundle last night and spent way more time than I should have on navigating documentation and following documentation for it still not to work. 

Please link to exactly what one is meant to do to get this working on a windows machine - again already using latest version of NodeLTS (16.1.0)

**Comment by vgidev** [comment]
Just purchased the product and it did not install. See npm log below. 
I am using Node 14.17.0 | Windows. 

Any suggestion?
I would appreciate a feedback asap.

Best,
Jose

$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: material-kit-pro-react@1.10.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@">= 15.4.1 < 17.0.0-0" from react-animate-on-scroll@2.1.5
npm ERR! node_modules/react-animate-on-scroll
npm ERR!   react-animate-on-scroll@"2.1.5" from the root project

**Comment by shkrwnd** [comment]
> Just purchased the product and it did not install. See npm log below.
> I am using Node 14.17.0 | Windows.
> 
> Any suggestion?
> I would appreciate a feedback asap.
> 
> Best,
> Jose
> 
> $ npm install
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: material-kit-pro-react@1.10.0
> npm ERR! Found: react@17.0.2
> npm ERR! node_modules/react
> npm ERR! react@"17.0.2" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@">= 15.4.1 < 17.0.0-0" from react-animate-on-scroll@2.1.5
> npm ERR! node_modules/react-animate-on-scroll
> npm ERR! react-animate-on-scroll@"2.1.5" from the root project

Is this issue resolved as I bought material design kit for react pro yesterday, and same error is there while doing the npm install 

`
While resolving: material-kit-pro-react@1.10.0
Found: react@17.0.2
node_modules/react
  react@"17.0.2" from the root project

Could not resolve dependency:
peer react@">= 15.4.1 < 17.0.0-0" from react-animate-on-scroll@2.1.5
node_modules/react-animate-on-scroll
  react-animate-on-scroll@"2.1.5" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "react",
    "version": "17.0.2",
    "whileInstalling": {
      "name": "material-kit-pro-react",
      "version": "1.10.0",
      "path": "/home/shikhar/Documents/ninja/material-kit-pro-react-v1.10.0"
    },
    "location": "node_modules/react",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "prod",
        "name": "react",
        "spec": "17.0.2",
        "from": {
          "location": "/home/shikhar/Documents/ninja/material-kit-pro-react-v1.10.0"
        }
      }
    ]
  },
  "currentEdge": {
    "type": "prod",
    "name": "react",
    "spec": "17.0.2",
    "from": {
      "location": "/home/shikhar/Documents/ninja/material-kit-pro-react-v1.10.0"
    }
  },
  "edge": {
    "type": "peer",
    "name": "react",
    "spec": ">= 15.4.1 < 17.0.0-0",
    "error": "INVALID",
    "from": {
      "name": "react-animate-on-scroll",
      "version": "2.1.5",
      "whileInstalling": {
        "name": "material-kit-pro-react",
        "version": "1.10.0",
        "path": "/home/shikhar/Documents/ninja/material-kit-pro-react-v1.10.0"
      },
      "location": "node_modules/react-animate-on-scroll",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "prod",
          "name": "react-animate-on-scroll",
          "spec": "2.1.5",
          "from": {
            "location": "/home/shikhar/Documents/ninja/material-kit-pro-react-v1.10.0"
          }
        }
      ]
    }
  },
  "strictPeerDeps": false,
  "force": false
}`

**Comment by AdrianeSantosDev** [comment]
Same issue here:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: material-kit-pro-react@1.9.0
npm ERR! Found: @material-ui/core@4.10.1
npm ERR! node_modules/@material-ui/core
npm ERR!   @material-ui/core@"4.10.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @material-ui/core@"^4.12.1" from @material-ui/lab@4.0.0-alpha.60
npm ERR! node_modules/@material-ui/lab
npm ERR!   @material-ui/lab@"^4.0.0-alpha.60" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

Had to go through all the documentation as well to know how to fix it, before, I even change all the WSL2 setup I was working on thinking that was the problem.
I was using Node.js 17.0.1 then downgrade to Node.js 16.13.0 (which is an LTS Version) then again to Node.js 14.18.1 and finally worked

I hope this is fixed soon

**Comment by kppetro** [comment]
Hi all,

Here is how you can fix this

1) Download [NVM](https://github.com/nvm-sh/nvm#installing-and-updating)

2) switch to node v14.17.5 (nvm use 14.17.5)

3) delete your node_modules folder and package-lock.json in project directory 

4) npm i && npm start

This will get you up and running at least while the other issues are fixed :)
