### ISSUE TITLE
[Bug] smoothScroll functionality not working

### ISSUE THREAD

**Issue by Bgjones15** [creativetimofficial/ct-material-kit-pro-react#87]
### Version
v1.10.0
### Reproduction link
https://demos.creative-tim.com/material-kit-pro-react/
### Operating System
Windows 10
### Device
PC
### Browser & Version
Chrome 91.0.4472.114
### Steps to reproduce
Click Sections > Projects on the header nav
Wait for page load
### What is expected?
Page loads and smooth scrolls to that section of the page
### What is actually happening?
Page turns white. If refreshed it loads, but at the top of the page.

---
### Additional comments
Accidently opened this issue on the non-pro github.

**Comment by sajadevo** [comment]
**Hi there**,

We've just updated the product to v2.0.0 and now its coming with a totally new structure, fresh design and new look.

**All the best**
**Sajad**
