### ISSUE TITLE
[Bug] creative tim material kit pro react does not apply css on reload

### ISSUE THREAD

**Issue by PierreVelluet** [creativetimofficial/ct-material-kit-pro-react#88]
### Version
last
### Reproduction link
https://github.com/PierreVelluet/yournextjourney_front.git
### Operating System
macos (last)
### Device
macbook pro
### Browser & Version
chrome (last)
### Steps to reproduce
Please clone the project above.
npm install
npm run dev

### What is expected?
Css loading after reload.
### What is actually happening?
Css is not apply on reload, though it is well apply on first run. I know im trying to use typescript with your product, which might be the problem (not sure though).

I am using tsconfig basrUrl & Paths for non relative import. The root file "global.d.ts" is here to avoid TS warnings on imports.

I really hope you can help me with this bug, since i am stuck for hours, and i would really love to use your product for my front-end.

Best regards, Pierre

---

**Comment by sajadevo** [comment]
**Hi there**,

We've just updated the product to v2.0.0 and now its coming with a totally new structure, fresh design and new look.

**All the best**
**Sajad**
