### ISSUE TITLE
[Bug] Problem with ESLint

### ISSUE THREAD

**Issue by trondkr** [creativetimofficial/ct-material-kit-pro-react#89]
### Version
1.10.0
### Reproduction link
https://www.oceanclimate.earth
### Operating System
Mac OS
### Device
Web
### Browser & Version
Google Chrome is up to date Version 92.0.4515.159 (Official Build) (x86_64)
### Steps to reproduce
Upgrade from Material React to Material React Pro.

run npm run install:clean

### What is expected?
Chrome opens up with the rendered website
### What is actually happening?
Development server starts and opens Chrome but then fails to show website with error: 
"Compiling...
Failed to compile.
"
src/assets/jss/material-kit-pro-react/components/cardStyle.js
  Line 1:1:  Definition for rule 'prettier/prettier' was not found  prettier/prettier
"
I assume I am missing an .eslintrc file or something but can not figure this out after using StackOverflow etc. I have the exact package.json file as the original Material React Pro and everything is installed correctly. 
Any help would be appreciated. 

---
### Solution
I am lacking one

**Comment by sajadevo** [comment]
**Hi there**,

We've just updated the product to v2.0.0 and now its coming with a totally new structure, fresh design and new look.

**All the best**
**Sajad**
