### ISSUE TITLE
[Bug] Pages become unclickable after file change/recompile until they are manually refreshed in the browser.

### ISSUE THREAD

**Issue by oguzhanozgul** [creativetimofficial/ct-material-kit-pro-react#91]
### Version
2.0.0
### Reproduction link
https://www.google.com
### Operating System
Windows 10
### Device
Desktop PC
### Browser & Version
Edge and chrome latest versions
### Steps to reproduce
Download Material Kit 2 Pro React.
Unzip and use npm install following the instructions on the website.
Open with code.
Open terminal
npm start in terminal.
-> after compilation, the presentation page shows correctly.
go to any file in the project, for example App.js
change any one line (for example, change the first import to zimport
save the file (won't compile)
change the zimport back to import, correcting the error
save the file (will compile)
go to browser, localhost:3000.
Page will become unclickable now (mouse cursor won't change when hovering over links, buttons won't click, when using F12 you won't be able to select any elements apart from html and body.
Hit F5 to refresh the page in the browser, now it works correctly.
### What is expected?
After file save, page to work normally.
### What is actually happening?
After file save, page displays with the updates but becomes unclickable.

---
### Solution
none.
### Additional comments
This is with a fresh install of the material kit 2 pro react, so I don't think it would be an error I made (note: there is a dependency error when npm installing @emotion/react needs a higher version. so I either change the required version or do npm install --force. This doesn't change the above explained behavior though.

**Comment by sajadevo** [comment]
**Hi @oguzhanozgul **

Thanks for using our product and helping us for making it better, we will fix the following issue on the next update of the product.

**All the best
Sajad**

**Comment by quimpocharles** [comment]
currently experiencing the same thing. any updates?

Edit: Upon inspection, an iframe element is generated when the page renders. Deleting the iframe element, allows users to access all links and buttons

Edit: Also seeing an error message in the console, "_Uncaught ReferenceError: process is not defined_".

**Comment by sajadevo** [comment]
**Hi there**

Please kindly update the react-scripts to its latest version its an issue with react-scripts.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad** 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)
