### ISSUE TITLE
[Bug] Rotating Card

### ISSUE THREAD

**Issue by TheDanishWonder** [creativetimofficial/ct-material-kit-pro-react#93]
### Version
2.0.0
### Reproduction link
https://Idonthaveareproduction.com
### Operating System
IOS
### Device
Iphone
### Browser & Version
Chrome - newest
### Steps to reproduce
1. step: tab card.
2. step: watch it turn white on backside on card.

-- it only happens on phone.
### What is expected?
turn to backside and display whatever has been implemented
### What is actually happening?
white card display, flip around again and the frontward appears as it is suppose to.

---
### Solution
don't have any yet.

**Comment by sajadevo** [comment]
**Hi @TheDanishWonder**

Thanks for using the product, its a problem with lower version of the browsers, but we will this issue on the next update of the product to make it working on lower version of the browsers as well.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/FhCJCaHdQa).**

**All the best,
Sajad**
