### ISSUE TITLE
[Bug] material-kit-2-pro-react-v2.0.0 Fails on NPM Install

### ISSUE THREAD

**Issue by SuzieZUMO** [creativetimofficial/ct-material-kit-pro-react#97]
### Version
material-kit-2-pro-react-v2.0.0
### Reproduction link
https://github.com/SuzieZUMO/MedExplainReact
### Operating System
Win 11 64
### Device
HP Envy 360
### Browser & Version
n/a, but latest Firefox
### Steps to reproduce
download the template
open folder in Visual Studio
Run NPM Install from cmd prompt
Get tons of errors.
### What is expected?
I am able to start with a working template. 
### What is actually happening?
PS C:\Users\sansp\OneDrive\Desktop\material-kit-2-pro-react-v2.0.0> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @mui/material@5.2.0
npm ERR! Found: @emotion/react@11.4.1
npm ERR! node_modules/@emotion/react
npm ERR!   @emotion/react@"11.4.1" from the root project
npm ERR!   peer @emotion/react@"^11.0.0-rc.0" from @emotion/styled@11.3.0
npm ERR!   node_modules/@emotion/styled
npm ERR!     @emotion/styled@"11.3.0" from the root project
npm ERR!     peerOptional @emotion/styled@"^11.3.0" from @mui/material@5.2.0
npm ERR!     node_modules/@mui/material
npm ERR!       @mui/material@"5.2.0" from the root project
npm ERR!       1 more (@mui/icons-material)
npm ERR!     1 more (@mui/styled-engine)
npm ERR!   1 more (@mui/styled-engine)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @emotion/react@"^11.5.0" from @mui/material@5.2.0
npm ERR! node_modules/@mui/material
npm ERR!   @mui/material@"5.2.0" from the root project
npm ERR!   peer @mui/material@"^5.0.0" from @mui/icons-material@5.2.0
npm ERR!   node_modules/@mui/icons-material
npm ERR!     @mui/icons-material@"5.2.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @emotion/react@11.9.0
npm ERR! node_modules/@emotion/react
npm ERR!   peerOptional @emotion/react@"^11.5.0" from @mui/material@5.2.0
npm ERR!   node_modules/@mui/material
npm ERR!     @mui/material@"5.2.0" from the root project
npm ERR!     peer @mui/material@"^5.0.0" from @mui/icons-material@5.2.0
npm ERR!     node_modules/@mui/icons-material
npm ERR!       @mui/icons-material@"5.2.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

---
### Solution
Am I missing something, or doing something wrong? 
### Additional comments
jsconfig.json:

{
  "compilerOptions": {
    "baseUrl": "src",
    "paths": {
      "*": ["src/*"]
    }
  }
}

**Comment by sajadevo** [comment]
**Hi @SuzieZUMO**

Thanks for using our product just run the following command `npm i --legacy-peer-deps`.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**

**Comment by SuzieZUMO** [comment]
Hi @sajadevo , 

I did that, but now I get this:

Compiled with problems:

ERROR in ./src/layouts/sections/page-sections/testimonials/components/TestimonialsTwo/index.js 24:0-64

Module not found: Error: Package path ./react/swiper-react is not exported from package C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper (see exports field in C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper\package.json)


ERROR in ./src/layouts/sections/page-sections/testimonials/components/TestimonialsTwo/index.js 26:0-31

Module not found: Error: Package path ./swiper.min.css is not exported from package C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper (see exports field in C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper\package.json)


ERROR in ./src/layouts/sections/page-sections/testimonials/components/TestimonialsTwo/index.js 27:0-54

Module not found: Error: Package path ./modules/navigation/navigation.min.css is not exported from package C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper (see exports field in C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper\package.json)


ERROR in ./src/pages/Blogs/SingleArticle/sections/Steps.js 24:0-64

Module not found: Error: Package path ./react/swiper-react is not exported from package C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper (see exports field in C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper\package.json)


ERROR in ./src/pages/Blogs/SingleArticle/sections/Steps.js 26:0-31

Module not found: Error: Package path ./swiper.min.css is not exported from package C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper (see exports field in C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper\package.json)


ERROR in ./src/pages/Blogs/SingleArticle/sections/Steps.js 27:0-54

Module not found: Error: Package path ./modules/navigation/navigation.min.css is not exported from package C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper (see exports field in C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper\package.json)


ERROR in ./src/pages/Company/Pricing/sections/Header.js 22:0-64

Module not found: Error: Package path ./react/swiper-react is not exported from package C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper (see exports field in C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper\package.json)


ERROR in ./src/pages/Company/Pricing/sections/Header.js 24:0-31

Module not found: Error: Package path ./swiper.min.css is not exported from package C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper (see exports field in C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper\package.json)


ERROR in ./src/pages/Company/Pricing/sections/Header.js 25:0-54

Module not found: Error: Package path ./modules/navigation/navigation.min.css is not exported from package C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper (see exports field in C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper\package.json)


ERROR in ./src/pages/Company/Pricing/sections/Testimonials.js 24:0-64

Module not found: Error: Package path ./react/swiper-react is not exported from package C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper (see exports field in C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper\package.json)


ERROR in ./src/pages/Company/Pricing/sections/Testimonials.js 26:0-31

Module not found: Error: Package path ./swiper.min.css is not exported from package C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper (see exports field in C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper\package.json)


ERROR in ./src/pages/Company/Pricing/sections/Testimonials.js 27:0-54

Module not found: Error: Package path ./modules/navigation/navigation.min.css is not exported from package C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper (see exports field in C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0\node_modules\swiper\package.json)


ERROR

Plugin "react" was conflicted between ".eslintrc.json" and "BaseConfig » C:\Users\sansp\node_modules\eslint-config-react-app\base.js".

**Comment by SuzieZUMO** [comment]
Hi @sajadevo ,
I started fresh. I unzipped the folder, then took only the material-kit-2-pro-react-v2.0.0 inside the parent material-kit-2-pro-react-v2.0.0 folder, and not taking the _MACOX folder. 
I opened the newly moved material-kit-2-pro-react-v2.0.0 folder in Visual Studio and ran npm i --legacy-peer-deps . 
I got the below (also see next comment):
PS C:\Users\sansp\source\repos\material-kit-2-pro-react-v2.0.0> npm i --legacy-peer-deps
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'material-kit-2-pro-react@2.0.0',
npm WARN EBADENGINE   required: { node: '14 || 15 || 16', npm: '>=6' },
npm WARN EBADENGINE   current: { node: 'v17.4.0', npm: '8.12.1' }
npm WARN EBADENGINE }
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

added 2046 packages, and audited 2047 packages in 2m

187 packages are looking for funding
  run `npm fund` for details

27 vulnerabilities (1 moderate, 19 high, 7 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

**Comment by SuzieZUMO** [comment]
Then I ran npm start and got this:

There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-jest": "^26.6.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-jest was detected higher up in the tree:

  C:\Users\sansp\node_modules\babel-jest (version: 27.5.1)

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "babel-jest" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if C:\Users\sansp\node_modules\babel-jest is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls babel-jest in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed babel-jest.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!

**Comment by SuzieZUMO** [comment]
I have been this far before and had tried following the instructions once (before I started over from a fresh unzip). 

I had deleted package-lock.json, then the node_modules folder, I didn't find babel-jest in package.json so I skipped that instruction. I ran npm install, but then it complained I was missing things in the node_modules folder.

**Comment by SuzieZUMO** [comment]
package.json

{
  "name": "material-kit-2-pro-react",
  "version": "2.0.0",
  "private": true,
  "author": "Creative Tim",
  "license": "See license in https://www.creative-tim.com/license",
  "description": "React version of Material Kit 2 PRO by Creative Tim",
  "homepage": "https://demos.creative-tim.com/material-kit-pro-react/#/",
  "bugs": {
    "url": "https://github.com/creativetimofficial/ct-material-kit-pro-react/issues"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/creativetimofficial/ct-material-kit-pro-react.git"
  },
  "engines": {
    "node": "14 || 15 || 16",
    "npm": ">=6"
  },
  "dependencies": {
    "@emotion/cache": "11.4.0",
    "@emotion/react": "11.4.1",
    "@emotion/styled": "11.3.0",
    "@mui/icons-material": "5.2.0",
    "@mui/material": "5.2.0",
    "@mui/styled-engine": "5.2.0",
    "@testing-library/jest-dom": "5.11.4",
    "@testing-library/react": "11.1.0",
    "@testing-library/user-event": "12.1.10",
    "chroma-js": "2.1.2",
    "flatpickr": "4.6.9",
    "prop-types": "15.7.2",
    "react": "17.0.2",
    "react-copy-to-clipboard": "5.0.4",
    "react-countup": "6.1.0",
    "react-dom": "17.0.2",
    "react-flatpickr": "3.10.7",
    "react-router-dom": "6.0.2",
    "react-scripts": "4.0.3",
    "react-syntax-highlighter": "15.4.5",
    "rellax": "1.12.1",
    "swiper": "7.3.4",
    "typed.js": "2.0.12",
    "uuid": "8.3.2",
    "web-vitals": "1.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "install:clean": "rm -rf node_modules/ && rm -rf package-lock.json && npm install && npm start"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "eslint": "7.30.0",
    "eslint-config-airbnb": "18.2.1",
    "eslint-config-prettier": "8.3.0",
    "eslint-plugin-import": "2.23.4",
    "eslint-plugin-jsx-a11y": "6.4.1",
    "eslint-plugin-prettier": "3.4.0",
    "eslint-plugin-react": "7.24.0",
    "eslint-plugin-react-hooks": "4.2.0",
    "prettier": "2.3.2"
  }
}

**Comment by SuzieZUMO** [comment]
Hi @sajadevo, 

Now I get the below:

Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (C:\Users\sansp\Source\Repos\material-kit-2-pro-react-v2.0.0\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\sansp\Source\Repos\material-kit-2-pro-react-v2.0.0\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\sansp\Source\Repos\material-kit-2-pro-react-v2.0.0\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\sansp\Source\Repos\material-kit-2-pro-react-v2.0.0\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\sansp\Source\Repos\material-kit-2-pro-react-v2.0.0\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\sansp\Source\Repos\material-kit-2-pro-react-v2.0.0\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\sansp\Source\Repos\material-kit-2-pro-react-v2.0.0\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\sansp\Source\Repos\material-kit-2-pro-react-v2.0.0\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
C:\Users\sansp\Source\Repos\material-kit-2-pro-react-v2.0.0\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (C:\Users\sansp\Source\Repos\material-kit-2-pro-react-v2.0.0\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\sansp\Source\Repos\material-kit-2-pro-react-v2.0.0\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\sansp\Source\Repos\material-kit-2-pro-react-v2.0.0\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\sansp\Source\Repos\material-kit-2-pro-react-v2.0.0\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\sansp\Source\Repos\material-kit-2-pro-react-v2.0.0\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\sansp\Source\Repos\material-kit-2-pro-react-v2.0.0\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\sansp\Source\Repos\material-kit-2-pro-react-v2.0.0\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\sansp\Source\Repos\material-kit-2-pro-react-v2.0.0\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.4.0

**Comment by SuzieZUMO** [comment]
I fixed the last error by changing to this:
 "start": "react-scripts --openssl-legacy-provider start",

But, why is it necessary to do? Is some of this outdated packages?

Also, is there a good tutorial on how to use this particular template?

Thank you!

**Comment by julesmorel** [comment]
After running `npm i --legacy-peer-deps`

The project fails to compile. The error is the following:

`Failed to compile.
src/components/MKPagination/index.js
  Line 32:28:  React Hook "useContext" is called conditionally. React Hooks must be called in the exact same order in every component render  react-hooks/rules-of-hooks
Search for the keywords to learn more about each error.`

**Comment by marlinjai** [comment]
no additional fixes? Please give some support for your paying customers :)

**Comment by sajadevo** [comment]
@marlinjai,

Could you please tell me your issue I'll assist you.

Regards,
Sajad

**Comment by marlinjai** [comment]
@sajadevo Thank you for helping me out. I am trying to use the Material 2 Kit Pro for React and I cant manage to use the components in my own project without using the whole Material project as a base. Following the quick start guide under: https://www.creative-tim.com/learning-lab/react/quick-start/material-kit/  It should work by following the guide from. the point packages but I cant get it to work. Following the exact steps of the quick start. Is there a video tutorial or sth I can follow along?

**Comment by marlinjai** [comment]
So if I understand it correctly I install the template using npm install that all works just fine. Then I create a new react app in another directory using npx create-react-app. After creating the new react app I should add all contents of the package.json file of the template to my own package .jsonf file.  

There comes my first question: Should I just add it or replace it with your file?

Then I should include the index.html as well as the src/ index.js and the jsconfig.js into my own project. 
I assume I should replace mine with the ones from the template right?

Then I import the whole asset folder into my project by just copying it inside my src folder.

Finally after  copying the following code to my own app.js : 

// @mui material components
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";

// Material Kit 2 React themes
import theme from "assets/theme";

<ThemeProvider theme={theme}>
  <CssBaseline />
  // ... your code goes here
</ThemeProvider>

And after installing the 

npm install @mui/system @emotion/react @emotion/styled --legacy-peer-deps

(without using --legacy-peer-deps I got a lot of errors)

I should finally be able to include the Material Kit 2 custom components

**Comment by sajadevo** [comment]
> So if I understand it correctly I install the template using npm install that all works just fine. Then I create a new react app in another directory using npx create-react-app. After creating the new react app I should add all contents of the package.json file of the template to my own package .jsonf file.
> 
> There comes my first question: Should I just add it or replace it with your file?
> 
> Then I should include the index.html as well as the src/ index.js and the jsconfig.js into my own project. I assume I should replace mine with the ones from the template right?
> 
> Then I import the whole asset folder into my project by just copying it inside my src folder.
> 
> Finally after copying the following code to my own app.js :
> 
> // @mui material components import { ThemeProvider } from "@mui/material/styles"; import CssBaseline from "@mui/material/CssBaseline";
> 
> // Material Kit 2 React themes import theme from "assets/theme";
> 
> // ... your code goes here
> And after installing the
> 
> npm install @mui/system @emotion/react @emotion/styled --legacy-peer-deps
> 
> (without using --legacy-peer-deps I got a lot of errors)
> 
> I should finally be able to include the Material Kit 2 custom components

Hey @marlinjai,

You're right this is the flow that you should do, is it's working for you or not please lemme know.

Regards,
Sajad

**Comment by rastaman** [comment]
I believe the patch i provide here: https://github.com/creativetimofficial/ct-material-kit-pro-react/issues/106 / https://gist.github.com/rastaman/3fe714f4f4977acd9c23d4f082def860 resolve this issue.

**Comment by sajadevo** [comment]
Hey everyone,

We've updated the product and this issue is fixed now.

Regards,
Sajad
