### ISSUE TITLE
[Bug] How to disable CustomDropDown

### ISSUE THREAD

**Issue by maratha1205** [creativetimofficial/ct-material-kit-pro-react#99]
### Version
1.8.0
### Reproduction link
https://codepen.io/maratha1205/pen/VwQRoJY
### Operating System
Windows 10
### Device
Laptop
### Browser & Version
Chrome
### Steps to reproduce
How to disable CustomDropdown programmatically?

### What is expected?
Disbaling customdropdown.
### What is actually happening?
Not disabling CustomDropdown.

---

**Comment by sajadevo** [comment]
**Hi @maratha1205**

Thanks for using our product, I can't get you correctly could you please make it more clear and descriptive that what exactly you want to do?

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
